
model:
  checkpoint: !SUB ${ckpt_path}

sample:
  seed: 2023
  batch_size: 128
  num_mols: !SUB ${num_mols}
  save_traj_prob: 0.0
  guidance:
    - uncertainty
    - 1.e-4
  num_steps: !SUB ${num_steps}
  pos_only: False
  center_pos_mode: protein