model:
  model_mean_type: C0  # ['noise', 'C0']
  loss_v_weight: 100.
  node_indicator: True
  center_pos_mode: protein
  sample_time_method: symmetric  # ['importance', 'symmetric']
  model_type: uni_o2
  num_layers: 6
  hidden_dim: 128
  n_heads: 16
  edge_feat_dim: 4  # edge type feat
  num_r_gaussian: 20
  knn: 32 
  num_node_types: 8
  act_fn: relu
  norm: True
  cutoff_mode: knn  # [radius, none]
  max_radius: 5.0
  ew_net_type: global  # [r, m, none]
  num_x2h: 1
  num_h2x: 1
  r_max: 10.
  x2h_out_fc: False
  sync_twoup: False
  name: diffusion
  node_dim: 128
  edge_dim: 64
  denoiser:
    backbone: NodeEdgeNet
    num_blocks: 6
    cutoff: 15
    use_gate: True
  diff:
    num_timesteps: 1000
    time_dim: 10
    categorical_space: discrete
    diff_pos:
      beta_schedule: advance
      scale_start: 0.9999
      scale_end: 0.0001
      beta_start: 1.e-7
      beta_end: 2.e-3
      width: 3
    diff_atom: 
      init_prob: tomask
      beta_schedule: advance
      scale_start: 0.9999
      scale_end: 0.0001
      width: 3
    diff_bond:
      init_prob: absorb
      beta_schedule: segment
      time_segment: [600, 400]
      segment_diff: 
        - scale_start: 0.9999
          scale_end: 0.001
          width: 3
        - scale_start: 0.001
          scale_end: 0.0001
          width: 2


train:
  seed: 2025
  batch_size: 8
  num_workers: 8
  pin_memory: True
  max_iters: 20000
  val_freq: 100
  pos_noise_std: 0.05
  max_grad_norm: 50.0
  use_amp: True
  optimizer:
    type: adamw
    lr: 1.e-4
    weight_decay: 1.e-8
    beta1: 0.99
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.8
    patience: 1000
    min_lr: 1.e-5

transform:
  use_mask_node: True
  use_mask_edge: True


data:
  name: pl
  path: !SUB ${path}
  split: !SUB ${split}
  transform:
    ligand_atom_mode: add_aromatic
    random_rot: False

chem:
  atomic_numbers: [6,7,8,9,15,16,17]  # C N O F P S Cl
  mol_bond_types: [1, 2, 3, 4]  # single, double, triple, aromatic
